/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Register */
        post: operations["post_register_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["post_login_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Attempt */
        post: operations["post_attempt_attempt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/next-task": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Next Task */
        get: operations["get_next_task_next_task_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/task/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Task Detail */
        get: operations["get_task_detail_task__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Modules */
        get: operations["get_modules_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/badges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Badges */
        get: operations["get_badges_badges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attempts */
        get: operations["get_attempts_attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Leaderboard */
        get: operations["get_leaderboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mastery-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mastery History */
        get: operations["get_mastery_history_mastery_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Run */
        post: operations["post_run_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/agent-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Logs */
        get: operations["get_agent_logs_admin_agent_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentLogItem */
        AgentLogItem: {
            /** Id */
            id: number;
            /** Sender */
            sender: string;
            /** Receiver */
            receiver: string;
            /** Performative */
            performative: string;
            /** Content */
            content: {
                [key: string]: unknown;
            } | null;
            /** Correlation Id */
            correlation_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AttemptItem */
        AttemptItem: {
            /** Id */
            id: number;
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            /** Submitted Query */
            submitted_query: string;
            /** Is Correct */
            is_correct: boolean;
            /** Error Type */
            error_type: string | null;
            /** Execution Time Ms */
            execution_time_ms: number | null;
            /** Rows Returned */
            rows_returned: number | null;
            /** Xp Awarded */
            xp_awarded: number;
            /** Hint Requested */
            hint_requested: boolean;
            /** Attempt Number */
            attempt_number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AttemptRequest */
        AttemptRequest: {
            /** Task Id */
            task_id: number;
            /** Submitted Query */
            submitted_query: string;
        };
        /** AttemptResponse */
        AttemptResponse: {
            feedback: components["schemas"]["FeedbackModel"];
            /** Xp Delta */
            xp_delta: number;
            /** Xp */
            xp: number;
            /** Level */
            level: number;
            /** Current Streak */
            current_streak: number;
            /** New Badges */
            new_badges: string[];
            recommendation: components["schemas"]["RecommendationModel"];
        };
        /**
         * BadgeCatalogItem
         * @description Katalog bedževa — bez `rule` (Prolog kriterij se ne izlaže klijentu).
         */
        BadgeCatalogItem: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Icon */
            icon: string | null;
            /** Xp Reward */
            xp_reward: number;
        };
        /** Body_post_login_login_post */
        Body_post_login_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /**
         * ConceptNode
         * @description `primary_task_count` (Faza 4.3 Stage 0, NALAZ #10) = broj AKTIVNIH PRIMARY
         *     taskova koncepta — ista semantika kao recommender_logic._concept_task_stats.
         *     UI iz njega zrcali Recommenderove kategorije (0 = glue · <2 = subfloor · >=2).
         */
        ConceptNode: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Order Index */
            order_index: number;
            /** Prerequisites */
            prerequisites: string[];
            /** Primary Task Count */
            primary_task_count: number;
        };
        /** ConceptRef */
        ConceptRef: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Is Primary */
            is_primary: boolean;
        };
        /** FeedbackModel */
        FeedbackModel: {
            /** Is Correct */
            is_correct?: boolean | null;
            /** Error Type */
            error_type?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LeaderboardItem
         * @description `xp` je score za dani scope (global = User.xp, weekly = SUM(delta) u prozoru).
         *     `level` je uvijek trenutni User.level.
         */
        LeaderboardItem: {
            /** Rank */
            rank: number;
            /** Username */
            username: string;
            /** Xp */
            xp: number;
            /** Level */
            level: number;
        };
        /**
         * MasteryHistoryPoint
         * @description Jedna točka BKT krivulje (snapshot p_l pri updateu).
         */
        MasteryHistoryPoint: {
            /** Concept */
            concept: string;
            /** P L */
            p_l: number;
            /** Attempt Id */
            attempt_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MasteryItem */
        MasteryItem: {
            /** Concept */
            concept: string;
            /** P L */
            p_l: number;
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** ModuleNode */
        ModuleNode: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Difficulty */
            difficulty: string;
            /** Order Index */
            order_index: number;
            /** Concepts */
            concepts: components["schemas"]["ConceptNode"][];
        };
        /** NextTaskResponse */
        NextTaskResponse: {
            /** Task Id */
            task_id?: number | null;
            /** Concept */
            concept?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** Page[AgentLogItem] */
        Page_AgentLogItem_: {
            /** Items */
            items: components["schemas"]["AgentLogItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[AttemptItem] */
        Page_AttemptItem_: {
            /** Items */
            items: components["schemas"]["AttemptItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[LeaderboardItem] */
        Page_LeaderboardItem_: {
            /** Items */
            items: components["schemas"]["LeaderboardItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ProfileResponse
         * @description Polja level-progresa i konstante (Faza 4.2) su tu da ih frontend NE
         *     hardkodira — izvor: gamification_logic (progress_to_next_level, LEVEL_STEP,
         *     MASTERY_THRESHOLD = mirror rules.pl mastery_threshold).
         */
        ProfileResponse: {
            /** Xp */
            xp: number;
            /** Level */
            level: number;
            /** Xp In Level */
            xp_in_level: number;
            /** Xp To Next */
            xp_to_next: number;
            /** Level Step */
            level_step: number;
            /** Mastery Threshold */
            mastery_threshold: number;
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Mastery */
            mastery: components["schemas"]["MasteryItem"][];
            /** Badges */
            badges: string[];
        };
        /** RecommendationModel */
        RecommendationModel: {
            /** Task Id */
            task_id?: number | null;
            /** Concept */
            concept?: string | null;
            /** Reason */
            reason?: string | null;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Username */
            username: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** RunRequest */
        RunRequest: {
            /** Task Id */
            task_id?: number | null;
            /** Query */
            query: string;
        };
        /** RunResponse */
        RunResponse: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Exec Ms */
            exec_ms: number;
            /** Error */
            error?: string | null;
        };
        /**
         * TaskDetailResponse
         * @description Detalj zadatka za studenta. NAMJERNO bez expected_query / expected_result /
         *     sandbox_schema — rješenje se NE izlaže kroz ovaj endpoint.
         */
        TaskDetailResponse: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Difficulty */
            difficulty: number;
            /** Estimated Time Sec */
            estimated_time_sec: number | null;
            /** Module Id */
            module_id: number;
            /** Concepts */
            concepts: components["schemas"]["ConceptRef"][];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_register_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_login_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_post_login_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    post_attempt_attempt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_next_task_next_task_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextTaskResponse"];
                };
            };
        };
    };
    get_profile_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponse"];
                };
            };
        };
    };
    get_task_detail_task__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_modules_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleNode"][];
                };
            };
        };
    };
    get_badges_badges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadgeCatalogItem"][];
                };
            };
        };
    };
    get_attempts_attempts_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AttemptItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_leaderboard_get: {
        parameters: {
            query?: {
                scope?: "global" | "weekly";
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeaderboardItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mastery_history_mastery_history_get: {
        parameters: {
            query?: {
                concept?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MasteryHistoryPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_run_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_logs_admin_agent_logs_get: {
        parameters: {
            query?: {
                correlation_id?: string | null;
                sender?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AgentLogItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
