"""add uq_attempts_user_task_number constraint

Revision ID: 158909aa016b
Revises: ccea7b154aec
Create Date: 2026-06-23 00:59:10.883566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158909aa016b'
down_revision: Union[str, Sequence[str], None] = 'ccea7b154aec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attempts_user_task_number', 'attempts', ['user_id', 'task_id', 'attempt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attempts_user_task_number', 'attempts', type_='unique')
    # ### end Alembic commands ###
