"""initial schema: 16 tables

Revision ID: ac6a5eeac6e5
Revises: 
Create Date: 2026-04-19 21:14:36.046856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac6a5eeac6e5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_messages_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sender', sa.String(length=50), nullable=False),
    sa.Column('receiver', sa.String(length=50), nullable=False),
    sa.Column('performative', sa.String(length=30), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_messages_correlation', 'agent_messages_log', ['correlation_id'], unique=False)
    op.create_index('idx_agent_messages_created', 'agent_messages_log', ['created_at'], unique=False)
    op.create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint("difficulty IN ('beginner', 'intermediate', 'advanced', 'expert', 'cross_module')", name='ck_modules_difficulty'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('xp', sa.Integer(), server_default='0', nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=20), server_default='student', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'admin')", name='ck_users_role'),
    sa.CheckConstraint('current_streak >= 0', name='ck_users_cstreak_nonneg'),
    sa.CheckConstraint('level >= 1', name='ck_users_level_min'),
    sa.CheckConstraint('longest_streak >= 0', name='ck_users_lstreak_nonneg'),
    sa.CheckConstraint('xp >= 0', name='ck_users_xp_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_xp_desc', 'users', [sa.text('xp DESC')], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.CheckConstraint("tier IN ('easy', 'medium', 'hard')", name='ck_concepts_tier'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_concepts_code', 'concepts', ['code'], unique=False)
    op.create_index('idx_concepts_module', 'concepts', ['module_id'], unique=False)
    op.create_table('misconceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('occurrences', sa.Integer(), server_default='1', nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_misconceptions_user_code')
    )
    op.create_index('idx_misconceptions_user', 'misconceptions', ['user_id'], unique=False)
    op.create_table('streaks',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('attempts_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'date')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sandbox_schema', sa.String(length=100), nullable=False),
    sa.Column('expected_query', sa.Text(), nullable=False),
    sa.Column('expected_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('estimated_time_sec', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_tasks_difficulty'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_active', 'tasks', ['is_active'], unique=False, postgresql_where='is_active = TRUE')
    op.create_index('idx_tasks_difficulty', 'tasks', ['difficulty'], unique=False)
    op.create_index('idx_tasks_module', 'tasks', ['module_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('submitted_query', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), server_default='0', nullable=False),
    sa.Column('hint_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name='ck_attempts_num_min'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempts_error_type', 'attempts', ['error_type'], unique=False, postgresql_where='error_type IS NOT NULL')
    op.create_index('idx_attempts_user_created', 'attempts', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_attempts_user_task', 'attempts', ['user_id', 'task_id'], unique=False)
    op.create_table('concept_prerequisites',
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('concept_id != prerequisite_id', name='ck_concept_prereq_self'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concept_id', 'prerequisite_id')
    )
    op.create_table('hints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('hint_text', sa.Text(), nullable=False),
    sa.Column('difficulty_min', sa.Integer(), server_default='1', nullable=False),
    sa.Column('difficulty_max', sa.Integer(), server_default='5', nullable=False),
    sa.Column('language', sa.String(length=5), server_default='hr', nullable=False),
    sa.CheckConstraint('difficulty_max BETWEEN 1 AND 5', name='ck_hints_diffmax'),
    sa.CheckConstraint('difficulty_min BETWEEN 1 AND 5', name='ck_hints_diffmin'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hints_error_concept', 'hints', ['error_type', 'concept_id'], unique=False)
    op.create_table('recommendations_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recommended_task_id', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.String(length=50), nullable=False),
    sa.Column('reasoning', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommended_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_user', 'recommendations_log', ['user_id', 'created_at'], unique=False)
    op.create_table('skill_mastery',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('p_l', sa.Float(), server_default='0.15', nullable=False),
    sa.Column('p_t', sa.Float(), server_default='0.20', nullable=False),
    sa.Column('p_g', sa.Float(), server_default='0.20', nullable=False),
    sa.Column('p_s', sa.Float(), server_default='0.10', nullable=False),
    sa.Column('attempts_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('correct_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('p_g BETWEEN 0 AND 1', name='ck_sm_p_g'),
    sa.CheckConstraint('p_l BETWEEN 0 AND 1', name='ck_sm_p_l'),
    sa.CheckConstraint('p_s BETWEEN 0 AND 1', name='ck_sm_p_s'),
    sa.CheckConstraint('p_t BETWEEN 0 AND 1', name='ck_sm_p_t'),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'concept_id')
    )
    op.create_table('task_concepts',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'concept_id')
    )
    op.create_index('idx_task_concepts_concept', 'task_concepts', ['concept_id'], unique=False)
    op.create_table('xp_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_xp_log_user_created', 'xp_log', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_xp_log_user_created', table_name='xp_log')
    op.drop_table('xp_log')
    op.drop_index('idx_task_concepts_concept', table_name='task_concepts')
    op.drop_table('task_concepts')
    op.drop_table('skill_mastery')
    op.drop_index('idx_recommendations_user', table_name='recommendations_log')
    op.drop_table('recommendations_log')
    op.drop_index('idx_hints_error_concept', table_name='hints')
    op.drop_table('hints')
    op.drop_table('concept_prerequisites')
    op.drop_index('idx_attempts_user_task', table_name='attempts')
    op.drop_index('idx_attempts_user_created', table_name='attempts')
    op.drop_index('idx_attempts_error_type', table_name='attempts', postgresql_where='error_type IS NOT NULL')
    op.drop_table('attempts')
    op.drop_table('user_badges')
    op.drop_index('idx_tasks_module', table_name='tasks')
    op.drop_index('idx_tasks_difficulty', table_name='tasks')
    op.drop_index('idx_tasks_active', table_name='tasks', postgresql_where='is_active = TRUE')
    op.drop_table('tasks')
    op.drop_table('streaks')
    op.drop_index('idx_misconceptions_user', table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index('idx_concepts_module', table_name='concepts')
    op.drop_index('idx_concepts_code', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index('idx_users_xp_desc', table_name='users')
    op.drop_table('users')
    op.drop_table('modules')
    op.drop_table('badges')
    op.drop_index('idx_agent_messages_created', table_name='agent_messages_log')
    op.drop_index('idx_agent_messages_correlation', table_name='agent_messages_log')
    op.drop_table('agent_messages_log')
    # ### end Alembic commands ###
